---
- name: Collect and gather system information from Linux servers
  hosts: all
  become: yes
  vars:
    csv_name: "{{ script_name | regex_replace('\\.sh$', '') }}.csv"
  tasks:
    - name: Upload the selected bash script to the host
      copy:
        src: "./{{ script_name }}"
        dest: "/tmp/{{ script_name }}"
        mode: '0755'

    - name: Execute the selected bash script to collect system information
      command: "/tmp/{{ script_name }} -f /tmp/{{ csv_name }}"

    - name: Fetch the generated CSV file from the host
      fetch:
        src: "/tmp/{{ csv_name }}"
        dest: "/tmp/fetched/"
        flat: yes

    - name: Write header to consolidated CSV on AWX server
      local_action:
        module: lineinfile
        path: "/tmp/consolidated_{{ csv_name }}"
        line: "Hostname,OS Name,OS Version,Apache Present,Apache Version,Nginx Present,Nginx Version,PHP Version,UFW Present,Open Ports in UFW,Fail2Ban Present,Fail2Ban Active,Active Jails,Reboot Required,Unattended Upgrades Installed,Sudo Users,Docker Installed,Docker Version,Root Login Permitted"
        create: yes
        state: present
      run_once: true
      delegate_to: localhost

    - name: Consolidate CSV files into one on the AWX server
      local_action:
        module: shell
        cmd: "cat /tmp/fetched/{{ csv_name }} >> /tmp/consolidated_{{ csv_name }}"
      with_fileglob:
        - "/tmp/fetched/*.csv"
      run_once: true
      delegate_to: localhost
